### ISSUE TITLE
assertion failed: slice.len() > 1 && slice.iter().all(|x| !x.is_nan())

### ISSUE THREAD

**Issue by zbraniecki** [bheisler/cargo-criterion#17]
when trying to use `cargo criterion` (on a clean repo and after `cargo bench`) I am getting:

```
thread 'main' panicked at 'assertion failed: slice.len() > 1 && slice.iter().all(|x| !x.is_nan())', /home/mozilla/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-criterion-1.0.0/src/stats/univariate/sample.rs:29:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })', /home/mozilla/.cargo/registry/src/github.com-1ecc6299db9ec823/criterion-0.3.3/src/benchmark.rs:573:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by emlun** [comment]
I'm seeing the same issue on [this commit](https://github.com/time-rs/time/tree/6efe950042e6ef71e3942cab7830267f6217aa65); `cargo bench` does not suffer the same issue.

Interestingly, it successfully runs the first benchmark and then crashes, then next time it crashes after 2 benchmarks, then after 3, and so on. After a `cargo clean` it starts over with crashing after one, then two, then three, etc. It seems like it's failing to read a previous report or something like that.


```
$ cargo-criterion --version
cargo-criterion 1.0.0


$ RUST_BACKTRACE=1 cargo-criterion
Finished bench [optimized] target(s) in 51.40s

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

Gnuplot not found, using plotters backend
Date: debug             time:   [143.39 ns 143.64 ns 143.93 ns]
thread 'main' panicked at 'assertion failed: slice.len() > 1 && slice.iter().all(|x| !x.is_nan())', /home/emlun/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-criterion-1.0.0/src/stats/univariate/sample.rs:29:9
stack backtrace:
  0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
  1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
  2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
  3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
  4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
  5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
  6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
  7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
  8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
  9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:486
 11: std::panicking::begin_panic
 12: <cargo_criterion::html::Html as cargo_criterion::report::Report>::history
 13: <cargo_criterion::report::Reports as cargo_criterion::report::Report>::history
 14: cargo_criterion::bench_target::BenchTarget::execute
 15: cargo_criterion::main
 16: std::rt::lang_start::{{closure}}
 17: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
 18: std::panicking::try::do_call
             at src/libstd/panicking.rs:297
 19: std::panicking::try
             at src/libstd/panicking.rs:274
 20: std::panic::catch_unwind
             at src/libstd/panic.rs:394
 21: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
 22: main
 23: __libc_start_main
 24: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


$ ls -l ../target/criterion/reports/
total 0
drwxr-xr-x 1 emlun emlun 230 11 okt 15.28 'Date_ debug'


$ RUST_BACKTRACE=1 cargo-criterion
Finished bench [optimized] target(s) in 0.05s

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

Gnuplot not found, using plotters backend
Date: debug             time:   [144.85 ns 145.08 ns 145.29 ns]
change: [+0.4400% +0.8528% +1.2917%] (p = 0.00 < 0.00)
Change within noise threshold.

Date: weeks_in_year_exhaustive
time:   [3.7906 us 3.7982 us 3.8074 us]
thread 'main' panicked at 'assertion failed: slice.len() > 1 && slice.iter().all(|x| !x.is_nan())', /home/emlun/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-criterion-1.0.0/src/stats/univariate/sample.rs:29:9
stack backtrace:
  0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
  1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
  2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
  3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
  4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
  5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
  6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
  7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
  8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
  9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:486
  11: std::panicking::begin_panic
  12: <cargo_criterion::html::Html as cargo_criterion::report::Report>::history
  13: <cargo_criterion::report::Reports as cargo_criterion::report::Report>::history
  14: cargo_criterion::bench_target::BenchTarget::execute
  15: cargo_criterion::main
  16: std::rt::lang_start::{{closure}}
  17: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  18: std::panicking::try::do_call
             at src/libstd/panicking.rs:297
  19: std::panicking::try
             at src/libstd/panicking.rs:274
  20: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  21: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  22: main
  23: __libc_start_main
  24: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


$ ls -l ../target/criterion/reports/
total 0
drwxr-xr-x 1 emlun emlun 418 11 okt 15.29 'Date_ debug'
drwxr-xr-x 1 emlun emlun 230 11 okt 15.29 'Date_ weeks_in_year_exhaustive'


$ RUST_BACKTRACE=1 cargo-criterion
Finished bench [optimized] target(s) in 0.04s

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

Gnuplot not found, using plotters backend
Date: debug             time:   [143.21 ns 143.44 ns 143.73 ns]
change: [-1.3671% -0.8448% -0.3495%] (p = 0.00 > 0.00)
No change in performance detected.

Date: weeks_in_year_exhaustive
time:   [3.8843 us 3.9370 us 3.9976 us]
change: [+3.0434% +4.4994% +5.9819%] (p = 0.00 < 0.00)
Change within noise threshold.

Date: test_monday_based_week
time:   [9.6456 ns 9.7725 ns 9.9411 ns]
thread 'main' panicked at 'assertion failed: slice.len() > 1 && slice.iter().all(|x| !x.is_nan())', /home/emlun/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-criterion-1.0.0/src/stats/univariate/sample.rs:29:9
stack backtrace:
  0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
  1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
  2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
  3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
  4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
  5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
  6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
  7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
  8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
  9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:486
  11: std::panicking::begin_panic
  12: <cargo_criterion::html::Html as cargo_criterion::report::Report>::history
  13: <cargo_criterion::report::Reports as cargo_criterion::report::Report>::history
  14: cargo_criterion::bench_target::BenchTarget::execute
  15: cargo_criterion::main
  16: std::rt::lang_start::{{closure}}
  17: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  18: std::panicking::try::do_call
             at src/libstd/panicking.rs:297
  19: std::panicking::try
             at src/libstd/panicking.rs:274
  20: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  21: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  22: main
  23: __libc_start_main
  24: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


$ ls -l ../target/criterion/reports/
total 0
drwxr-xr-x 1 emlun emlun 418 11 okt 15.29 'Date_ debug'
drwxr-xr-x 1 emlun emlun 230 11 okt 15.29 'Date_ test_monday_based_week'
drwxr-xr-x 1 emlun emlun 418 11 okt 15.29 'Date_ weeks_in_year_exhaustive'
```

**Comment by zbraniecki** [comment]
I'm still seeing this and still am able to workaround the way @emlun suggested - crash, redo, test passes.

**Comment by eaglgenes101** [comment]
Can also confirm. It seems like such a weird bug, especially since `cargo bench` has no problem with doing a first run all the way through.

**Comment by bheisler** [comment]
Hey folks; I've pushed a change that I hope will fix this. Could you try installing the latest git version and see if that helps?

**Comment by zbraniecki** [comment]
Yup! I did:
```
cargo clean
cargo criterion // <-- crashes
cargo uninstall cargo-criterion
cargo install cargo-criterion --git https://github.com/bheisler/cargo-criterion --branch main
cargo clean
cargo criterion // <-- works
```

Thank you!

**Comment by bheisler** [comment]
Thanks! I've published a new version with this fix.

**Comment by sdht0** [comment]
The README command `cargo install cargo-criterion --version 1.0.0` should be changed to not have the version. I just faced this bug because I followed the instructions and did not get the fix.

**Comment by bheisler** [comment]
Good point, thanks!
